apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: rubin-jekins-workers
spec:
  hosts:
  - ci.lsst.codes
  ports:
  - number: 443
    name: tls
    protocol: TLS
  resolution: DNS
---

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-egressgateway
spec:
  selector:
    istio: egressgateway
  servers:
  - port:
      number: 443
      name: tls
      protocol: TLS
    hosts:
    - ci.lsst.codes
    tls:
      mode: PASSTHROUGH
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: egressgateway-for-rubin-jenkins-workers
spec:
  host: istio-egressgateway.istio-system.svc.cluster.local
  subsets:
  - name: rubin-jenkins-workers
  #- name: ci.lsst.codes
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: direct-rubin-jenkins-workers-through-egress-gateway
spec:
  hosts:
  - ci.lsst.codes
  gateways:
  - mesh
  - istio-egressgateway
  tls:
  - match:
    - gateways:
      - mesh
      port: 443
      sniHosts:
      - ci.lsst.codes
    route:
    - destination:
        host: istio-egressgateway.istio-system.svc.cluster.local
        #subset: ci.lsst.codes
        subset: rubin-jenkins-workers
        port:
          number: 443
  - match:
    - gateways:
      - istio-egressgateway
      port: 443
      sniHosts:
      - ci.lsst.codes
    route:
    - destination:
        host: ci.lsst.codes
        port:
          number: 443
      weight: 100



